/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papersystem;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Abbasi
 */
public class FixedData extends javax.swing.JPanel {

    /**
     * Creates new form fixedData
     */
    public FixedData() {
        initComponents();
        bGenerateFixed.setIcon((new ImageIcon(getClass().getResource(("gen.png")))));
        bGenerateFixed.setBorderPainted(false);
        bGenerateFixed.setFocusPainted(false);
        bGenerateFixed.setContentAreaFilled(false);
        informationFixed.setEditable(false);
//        timeUnitsFixed.removeAllItems();
//        timeUnitsFixed.addItem("Mins");
//        timeUnitsFixed.addItem("Hrs");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGenerateFixed = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        instructionsFixed = new javax.swing.JTextArea();
        timeFixed = new javax.swing.JTextField();
        timeUnitsFixed = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        informationFixed = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        dateFixed = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(249, 249, 249));
        setOpaque(false);

        bGenerateFixed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bGenerateFixed.setText("Generate Paper");
        bGenerateFixed.setOpaque(false);
        bGenerateFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerateFixedActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Instructions:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Time:");

        instructionsFixed.setColumns(20);
        instructionsFixed.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        instructionsFixed.setRows(5);
        jScrollPane3.setViewportView(instructionsFixed);

        timeFixed.setToolTipText("Enter Time");
        timeFixed.setName(""); // NOI18N
        timeFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFixedActionPerformed(evt);
            }
        });

        timeUnitsFixed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mins", "Hrs" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Information:");

        informationFixed.setColumns(20);
        informationFixed.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        informationFixed.setRows(5);
        jScrollPane2.setViewportView(informationFixed);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
            .addComponent(jLabel1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(bGenerateFixed))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(dateFixed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(timeFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(timeUnitsFixed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(timeFixed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeUnitsFixed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dateFixed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bGenerateFixed))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bGenerateFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerateFixedActionPerformed

    }//GEN-LAST:event_bGenerateFixedActionPerformed

    private void timeFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFixedActionPerformed

    }//GEN-LAST:event_timeFixedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bGenerateFixed;
    public org.jdesktop.swingx.JXDatePicker dateFixed;
    public javax.swing.JTextArea informationFixed;
    public javax.swing.JTextArea instructionsFixed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField timeFixed;
    public javax.swing.JComboBox timeUnitsFixed;
    // End of variables declaration//GEN-END:variables
}
